# Generated by Django 4.2.3 on 2023-10-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fmkorea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('shop', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
                ('deliver', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ppomppu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ruliweb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
    ]
