# Generated by Django 4.2.3 on 2023-11-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmkorea',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ppomppu',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ruliweb',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
