# Generated by Django 4.2.3 on 2023-11-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppomppu',
            name='number',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ruliweb',
            name='number',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
