name: CI/CD

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and push Docker image
      run: |
        docker build -t hyongkui/hot_deal .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push hyongkui/hot_deal

    - name: Deploy to AWS EC2
      run: |
        # Add your deployment steps here (e.g., SSH into EC2 and pull the Docker image)
        docker pull hyongkui/hot_deal
        docker run -d -p 8080:8080 hyongkui/hot_deal

#    - name: Update database schema (if needed)
#      run: |
#        # Add your database migration steps here
#
#    - name: Deploy to AWS RDS
#      run: |
#        # Add your steps to deploy to AWS RDS

    - name: Send deployment notification
      run: echo "Deployment completed successfully!"